--changelog-file

-- liquibase formatted sql

--changeset : category and category types creation and insertions
DROP TABLE IF EXISTS category_type;
DROP TABLE IF EXISTS category;

CREATE TABLE category
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(50) NOT NULL,
    value       VARCHAR(50) NOT NULL,
    description VARCHAR(200)
);

CREATE TABLE category_type
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(50) NOT NULL,
    description      VARCHAR(200),

    has_params       BOOLEAN,
    params_max_count smallint,

    sample1          VARCHAR(100),
    sample1          VARCHAR(100),
    sample1          VARCHAR(100),


    value            VARCHAR(50) NOT NULL,

    category_id      BIGINT      NOT NULL,
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES category (id)
);

INSERT INTO category (id, description, name, value) VALUES (1, 'Personal data (first names, last names, etc.)', 'Person Names', 'name');
INSERT INTO category (id, description, name, value) VALUES (2, 'Full-fledged address data, has more than 20 possible options for composing an address', 'Address Line', 'address');
INSERT INTO category (id, description, name, value) VALUES (3, 'Country, has more possible options', 'Country', 'country');
INSERT INTO category (id, description, name, value) VALUES (4, 'Date time with optional patterns and durations', 'Date Time', 'date');
INSERT INTO category (id, description, name, value) VALUES (5, 'Duration object representing a random duration of minutes in the given range', 'Duration Minites', 'duration');
INSERT INTO category (id, description, name, value) VALUES (6, 'Number with optionals min and max values', 'Scoped Random Number', 'number');
INSERT INTO category (id, description, name, value) VALUES (7, 'Phone number with optionals min and max values', 'Phone Number', 'phoneNumber');
INSERT INTO category (id, description, name, value) VALUES (8, 'Email with optionals min and max values', 'Email Address', 'internet');
INSERT INTO category (id, description, name, value) VALUES (9, 'Random boolean', 'Random Boolean', 'boolean');
INSERT INTO category (id, description, name, value) VALUES (10, 'Random text, has more possible options', 'Text', 'text');

-- add base class methods in datafaker class
-- Class Name: Name
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (1, 'Female First (Given) Name', 'Returns a random female ''given'' name. has no parameters', false, 'femaleFirstName', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (2, 'First (Given) Name', 'Returns a random ''given'' name such as Aaliyah, Aaron, Abagail or Abbey has no parameters', false, 'firstName', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (3, 'FullName', 'Returns the same value as name() has no parameters', false, 'fullName', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (4, 'LastName', 'Returns a random last name such as Smith, Jones or Baldwin, has no parameters', false, 'lastName', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (5, 'Male First Name', 'Returns a random male ''given'' name. has no parameters', false, 'maleFirstName', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (6, 'Optional Prefixed Fist&Last Name', 'A multipart name composed of an optional prefix, a firstname and a lastname or other possible variances based on locale. has no parameters', false, 'name', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (7, 'Optional Pre/Suffixed Full Name', 'A multipart name composed of an optional prefix, a given and family name, another ''firstname'' for the middle name and an optional suffix such as Jr. has no parameters', false, 'nameWithMiddle', 0, 1);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (8, 'Name with Title', 'A three part title composed of a descriptor level and job. has no parameters', false, 'title', 0, 1);

-- Class Name: Address
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (9, 'City', 'Random city. has no parameters', false, 'city', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (10, 'City Name', 'Random city name. has no parameters', false, 'cityName', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (11, 'City Prefix', 'Random city prefix. has no parameters', false, 'cityPrefix', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (12, 'City Suffix', 'Random city suffix. has no parameters', false, 'citySuffix', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (13, 'Country Name', 'Country name. has no parameters', false, 'country', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (14, 'Country Code', 'Random country code. has no parameters', false, 'countryCode', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (15, 'Building Number', 'Random building number. has no parameters', false, 'buildingNumber', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (16, 'Full Address', 'Full address. has no parameters', false, 'fullAddress', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (17, 'Latitude', 'Random latitude. has no parameters', false, 'latitude', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (18, 'Longitude', 'Random longitude. has no parameters', false, 'longitude', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (19, 'Lat/Lon with Delimiter', 'Returns the lat/lon coordinates formatted as lat delimiter lon. has one String delimiter parameter', true, 'latLon', 1, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (20, 'Lat/Lon', 'Returns the lat/lon coordinates formatted as lat,lon. has no parameter', false, 'latLon', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (21, 'Lon/Lat with Delimiter', 'Returns the lat/lon coordinates formatted as lon delimiter lat. has one String delimiter parameter', true, 'lonLat', 1, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (22, 'Lon/Lat with Delimiter', 'Returns the lat/lon coordinates formatted as lon,lat. has no parameter', false, 'lonLat', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (23, 'TimeZone', 'Random timeZone. has no parameters', false, 'tineZone', 0, 2);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (24, 'States', 'Random state. has no parameters', false, 'state', 0, 2);


-- Class Name: Country
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (25, 'Country Name', 'Returns a random country name. has no parameters', false, 'country', 0, 3);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (26, 'Country Code2', 'Returns a random country code. has no parameters', false, 'countryCode2', 0, 3);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (27, 'Currency (Name)', 'Returns a random currency name. has no parameters', false, 'currency', 0, 3);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (28, 'Capital', 'Returns a random capital. has no parameters', false, 'capital', 0, 3);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (29, 'Currency Code', 'Returns a random currency code. has no parameters', false, 'currencyCode', 0, 3);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (30, 'Country Flag', 'Returns a random flag. has no parameters', false, 'flag', 0, 3);

-- Class Name: Date
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (31, 'BithDate as Timestamp', 'Returns a random birth date, type Timestamp. has no parameters', false, 'birthday', 0, 4);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (32, 'BirthDate as String with Pattern', 'Generates and converts to string representation a random birthday, type String. has one pattern', true, 'birthday', 1, 4);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (33, 'BirthDate', 'Generates a random birthday between two ages from now, type Timestamp. has two parameters', true, 'birthday', 2, 4);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (34, 'BirthDate with Range', 'Generates and converts to string representation a random birthday between two ages from now, type String. has three parameters minAge, maxAge, pattern', true, 'birthday', 3, 4);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (35, 'Duration with Max', 'Generates a random Duration lower than max, type Duration. has two parameters (Long max, String unit)', true, 'duration', 2, 4);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (36, 'Duration in Min - Max', 'Generates a random Duration between min and max., type Duration. has three parameters (Long min, Long max, String unit)', true, 'duration', 3, 4);

-- Class Name: Duration
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (37, 'Duration with scoped days', 'Duration object representing a random duration of days in the given range. has one parameter (Long daysMax)', true, 'atMostDays', 1, 5);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (38, 'Duration with scoped hours', 'Returns a Duration object representing a random duration of hours in the given range. has one parameter (Long hoursMax)', true, 'atMostHours', 1, 5);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (39, 'Duration with scoped minites', 'Duration object representing a random duration of minutes in the given range. has one parameter (Long minutesMax)', true, 'atMostMinutes', 1, 5);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (40, 'Duration with scoped seconds', 'Duration object representing a random duration of seconds in the given range. has one parameter (Long secondsMax)', true, 'atMostSeconds', 1, 5);

-- Class Name: Number
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (41, 'Digit', 'Returns a random digit. has no parameters', false, 'digit', 0, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (42, 'Digit with count', 'Returns a random digits, has one parameter (int count)', true, 'digits', 1, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (43, 'Positive', 'Returns a positive number, has no parameters', false, 'positive', 0, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (44, 'Negative', 'Random negative number, has no parameters', false, 'negative', 0, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (45, 'Number in Between', 'Random number in the given range, has two parameters (int min, int max)', true, 'numberBetween', 2, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (46, 'Number [0-9]', 'Returns a random number from 0-9 (both inclusive), has no parameters', false, 'randomDigit', 0, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (47, 'Number [1-9]', 'Returns a random number from 1-9 (both inclusive), has no parameters', false, 'randomDigitNotZero', 0, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (48, 'Double in range', 'Returns a random double, has parameters (int maxNumberOfDecimals, long min, long max)', true, 'randomDouble', 3, 6);
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (49, 'Random Number', 'Returns a random number, has no parameters', false, 'randomNumber', 0, 6);

-- Class Name: PhoneNumber
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (50, 'Phone Number', 'Random phone number. has no parameters', false, 'phoneNumber', 0, 7);

-- Class Name: Internet
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (51, 'Email', 'Random email. has no parameters', false, 'emailAddress', 0, 8);

-- Class Name: Bool
INSERT INTO category_type (id, name, description, has_params, value, params_max_count, category_id) VALUES (52, 'Bool', 'Random boolean. has no parameters', false, 'bool', 0, 9);