spring:
  thread-executor: virtual
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/data_faker_db
    user: user
    password: pass
  datasource:
    url: jdbc:postgresql://localhost:5432/data_faker_db
    username: user
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect

springdoc:
  swagger-ui:
    path: /swagger/doc
    operationsSorter: method
  api-docs:
    path: /swagger/api-docs

server:
  port: 9090
