spring:
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 3600000
  thread-executor: virtual
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/data_faker_db
    user: user
    password: pass
    liquibase-schema: faker
    default-schema: faker
  datasource:
    url: jdbc:postgresql://localhost:5432/data_faker_db
    username: user
    password: pass
    hikari:
      schema: faker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger/doc
    operationsSorter: method
  api-docs:
    path: /swagger/api-docs

server:
  port: 9090